# Spotify API credentials
SPOTIPY_CLIENT_ID = "your_SPOTIPY_CLIENT_ID_here"
SPOTIPY_CLIENT_SECRET = "your_SPOTIPY_CLIENT_SECRET_here"
SPOTIPY_REDIRECT_URI = "your_SPOTIPY_REDIRECT_URI_here"

# Unsplash API key
UNSPLASH_ACCESS_KEY = "your_UNSPLASH_ACCESS_KEY_here"